# Form implementation generated from reading ui file 'Neonui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NeonGUI(object):
    def setupUi(self, NeonGUI):
        NeonGUI.setObjectName("NeonGUI")
        NeonGUI.resize(1121, 717)
        self.centralwidget = QtWidgets.QWidget(parent=NeonGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -20, 1141, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Jithu/Downloads/7LP8.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 390, 221, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/Jithu/Downloads/XDZT.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(830, 490, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 0);\n"
"\n"
"\n"
"selection-background-color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(920, 490, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"background-color: rgb(238, 8, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"selection-background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 411, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/Jithu/Downloads/Jarvis_Loading_Screen.gif"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(600, 30, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:white;\n")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(850, 30, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:white;\n")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 600, 1111, 121))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/Jithu/Downloads/D4Ll.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        NeonGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(NeonGUI)
        QtCore.QMetaObject.connectSlotsByName(NeonGUI)

    def retranslateUi(self, NeonGUI):
        _translate = QtCore.QCoreApplication.translate
        NeonGUI.setWindowTitle(_translate("NeonGUI", "MainWindow"))
        self.pushButton.setText(_translate("NeonGUI", "RUN"))
        self.pushButton_2.setText(_translate("NeonGUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NeonGUI = QtWidgets.QMainWindow()
    ui = Ui_NeonGUI()
    ui.setupUi(NeonGUI)
    NeonGUI.show()
    sys.exit(app.exec())
